#!/bin/sh

touch args.tmp
echo "ld a,  $2" >> args.tmp
echo "ld bc, $3" >> args.tmp
echo "ld de, $4" >> args.tmp
echo "ld hl, $5" >> args.tmp

cat head.asm args.tmp $1 > asm.tmp

./rgbasm -o tmp.o ./asm.tmp && ./rgblink -o ./tmp.gb ./tmp.o && ./rgbfix -p 255 ./tmp.gb

./cboy ./bootrom/bootrom.bin ./tmp.gb $af $bc $de $hl
rm ./args.tmp ./tmp.o ./asm.tmp ./tmp.gb
